<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\Department;
use App\Models\Position;
use App\Models\FamilyComposition;
use App\Models\EmploymentStatus;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EmployeesTableSeeder50 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data to avoid duplicates
        DB::table('employees')->delete();

        // Get department records
        $productionDept = Department::where('name', 'Production')->first();
        $salesDept = Department::where('name', 'Sales')->first();
        $financeDept = Department::where('name', 'Finance')->first();
        $hrDept = Department::where('name', 'HR')->first();
        $itDept = Department::where('name', 'IT')->first();
        $adminDept = Department::where('name', 'Admin')->first() ?? Department::first();
        $warehouseDept = Department::where('name', 'Warehouse')->first() ?? Department::skip(1)->first();
        $logisticsDept = Department::where('name', 'Logistics')->first() ?? Department::skip(2)->first();
        $maintenanceDept = Department::where('name', 'Maintenance')->first() ?? Department::skip(3)->first();
        $qualityControlDept = Department::where('name', 'Quality Control')->first() ?? Department::skip(4)->first();

        // Get position records
        $foremanPos = Position::where('name', 'Foreman')->first();
        $salesManagerPos = Position::where('name', 'Sales Manager')->first();
        $financeOfficerPos = Position::where('name', 'Finance Officer')->first();
        $operatorPos = Position::where('name', 'Operator')->first();
        $hrManagerPos = Position::where('name', 'HR Manager')->first();
        $itSupportPos = Position::where('name', 'IT Support')->first();
        $directorPos = Position::where('name', 'Director')->first();
        $supervisorPos = Position::where('name', 'Supervisor')->first();
        $managerPos = Position::where('name', 'Manager')->first() ?? Position::first();
        $assistantPos = Position::where('name', 'Assistant')->first() ?? Position::skip(1)->first();
        $staffPos = Position::where('name', 'Staff')->first() ?? Position::skip(2)->first();
        $engineerPos = Position::where('name', 'Engineer')->first() ?? Position::skip(3)->first();
        $adminStaffPos = Position::where('name', 'Admin Staff')->first() ?? Position::skip(4)->first();
        $warehouseStaffPos = Position::where('name', 'Warehouse Staff')->first() ?? Position::skip(5)->first();
        $logisticsStaffPos = Position::where('name', 'Logistics Staff')->first() ?? Position::skip(6)->first();

        // Get family composition records
        $family1 = FamilyComposition::where('name', 'TK/1')->first();
        $family2 = FamilyComposition::where('name', 'TK/2')->first();
        $family3 = FamilyComposition::where('name', 'TK/3')->first();
        $family4 = FamilyComposition::where('name', 'TK/4')->first();
        $family5 = FamilyComposition::where('name', 'TK/5')->first();
        $family6 = FamilyComposition::where('name', 'TK/6')->first() ?? FamilyComposition::first();
        $family7 = FamilyComposition::where('name', 'TK/7')->first() ?? FamilyComposition::skip(1)->first();
        $family8 = FamilyComposition::where('name', 'TK/8')->first() ?? FamilyComposition::skip(2)->first();

        // Get employment status records
        $statusActive = EmploymentStatus::where('value', 'active')->first();
        $statusInactive = EmploymentStatus::where('value', 'inactive')->first();
        $statusResigned = EmploymentStatus::where('value', 'resigned')->first() ?? EmploymentStatus::first();

        $employees = [
            [
                'ndp' => 'EMP001',
                'name' => 'Budi Santoso',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Foreman',
                'position_id' => $foremanPos?->id,
                'grade' => 'B2',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 7500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-01-15',
                'address' => 'Jl. Merdeka No. 123, Jakarta',
                'phone' => '081234567890',
                'email' => 'budi.santoso@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP002',
                'name' => 'Siti Rahayu',
                'department' => 'Sales',
                'department_id' => $salesDept?->id,
                'position' => 'Sales Manager',
                'position_id' => $salesManagerPos?->id,
                'grade' => 'A1',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 12000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2019-03-20',
                'address' => 'Jl. Sudirman No. 456, Jakarta',
                'phone' => '081298765432',
                'email' => 'siti.rahayu@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP003',
                'name' => 'Ahmad Prabowo',
                'department' => 'Finance',
                'department_id' => $financeDept?->id,
                'position' => 'Finance Officer',
                'position_id' => $financeOfficerPos?->id,
                'grade' => 'C1',
                'family_composition' => $family5?->name,
                'family_composition_id' => $family5?->id,
                'monthly_salary' => 8500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-07-10',
                'address' => 'Jl. Gatot Subroto No. 789, Jakarta',
                'phone' => '085678901234',
                'email' => 'ahmad.prabowo@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP004',
                'name' => 'Dewi Kurniawati',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Operator',
                'position_id' => $operatorPos?->id,
                'grade' => 'C2',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 5500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-02-05',
                'address' => 'Jl. Thamrin No. 321, Jakarta',
                'phone' => '089876543210',
                'email' => 'dewi.kurniawati@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP005',
                'name' => 'Rina Wijaya',
                'department' => 'HR',
                'department_id' => $hrDept?->id,
                'position' => 'HR Manager',
                'position_id' => $hrManagerPos?->id,
                'grade' => 'A2',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 10000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2019-06-15',
                'address' => 'Jl. Rasuna Said No. 111, Jakarta',
                'phone' => '082134567890',
                'email' => 'rina.wijaya@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP006',
                'name' => 'Eko Prasetyo',
                'department' => 'IT',
                'department_id' => $itDept?->id,
                'position' => 'IT Support',
                'position_id' => $itSupportPos?->id,
                'grade' => 'B1',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 7000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-09-01',
                'address' => 'Jl. Casablanca No. 88, Jakarta',
                'phone' => '082198765432',
                'email' => 'eko.prasetyo@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP007',
                'name' => 'Hartono Sukarno',
                'department' => 'Sales',
                'department_id' => $salesDept?->id,
                'position' => 'Sales Manager',
                'position_id' => $salesManagerPos?->id,
                'grade' => 'A1',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 11500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2018-04-10',
                'address' => 'Jl. Sudirman No. 200, Jakarta',
                'phone' => '083456789012',
                'email' => 'hartono.sukarno@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP008',
                'name' => 'Lisa Permata',
                'department' => 'Finance',
                'department_id' => $financeDept?->id,
                'position' => 'Finance Officer',
                'position_id' => $financeOfficerPos?->id,
                'grade' => 'C1',
                'family_composition' => $family1?->name,
                'family_composition_id' => $family1?->id,
                'monthly_salary' => 8000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-01-20',
                'address' => 'Jl. Gatot Subroto No. 500, Jakarta',
                'phone' => '084567890123',
                'email' => 'lisa.permata@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP009',
                'name' => 'Andi Kusuma',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Supervisor',
                'position_id' => $supervisorPos?->id,
                'grade' => 'B3',
                'family_composition' => $family6?->name,
                'family_composition_id' => $family6?->id,
                'monthly_salary' => 9000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2017-08-15',
                'address' => 'Jl. Pangeran Jayakarta No. 33, Jakarta',
                'phone' => '085678901234',
                'email' => 'andi.kusuma@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP010',
                'name' => 'Maya Sari',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Operator',
                'position_id' => $operatorPos?->id,
                'grade' => 'C2',
                'family_composition' => $family1?->name,
                'family_composition_id' => $family1?->id,
                'monthly_salary' => 5200000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-05-10',
                'address' => 'Jl. Mangga Dua No. 77, Jakarta',
                'phone' => '086789012345',
                'email' => 'maya.sari@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP011',
                'name' => 'Bambang Sutrisno',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Operator',
                'position_id' => $operatorPos?->id,
                'grade' => 'C2',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 5400000,
                'status' => 'inactive',
                'employment_status_id' => $statusInactive?->id,
                'hire_date' => '2019-11-20',
                'address' => 'Jl. Hayam Wuruk No. 155, Jakarta',
                'phone' => '087890123456',
                'email' => 'bambang.sutrisno@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP012',
                'name' => 'Diana Putri',
                'department' => 'IT',
                'department_id' => $itDept?->id,
                'position' => 'Director',
                'position_id' => $directorPos?->id,
                'grade' => 'A1',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 25000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2015-03-01',
                'address' => 'Jl. Senayan No. 99, Jakarta',
                'phone' => '088901234567',
                'email' => 'diana.putri@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP013',
                'name' => 'Joko Widodo',
                'department' => 'Admin',
                'department_id' => $adminDept?->id,
                'position' => 'Admin Staff',
                'position_id' => $adminStaffPos?->id,
                'grade' => 'C1',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 6000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-04-12',
                'address' => 'Jl. Kebon Sirih No. 45, Jakarta',
                'phone' => '089901234568',
                'email' => 'joko.widodo@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP014',
                'name' => 'Tina Novianti',
                'department' => 'Warehouse',
                'department_id' => $warehouseDept?->id,
                'position' => 'Warehouse Staff',
                'position_id' => $warehouseStaffPos?->id,
                'grade' => 'C3',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 5300000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-01-30',
                'address' => 'Jl. Diponegoro No. 120, Jakarta',
                'phone' => '081287654321',
                'email' => 'tina.novianti@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP015',
                'name' => 'Agus Kurniawan',
                'department' => 'Logistics',
                'department_id' => $logisticsDept?->id,
                'position' => 'Logistics Staff',
                'position_id' => $logisticsStaffPos?->id,
                'grade' => 'C2',
                'family_composition' => $family1?->name,
                'family_composition_id' => $family1?->id,
                'monthly_salary' => 5600000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-11-05',
                'address' => 'Jl. Kramat Raya No. 205, Jakarta',
                'phone' => '082276543210',
                'email' => 'agus.kurniawan@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP016',
                'name' => 'Fitri Lestari',
                'department' => 'Quality Control',
                'department_id' => $qualityControlDept?->id,
                'position' => 'Staff',
                'position_id' => $staffPos?->id,
                'grade' => 'B1',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 6800000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-06-18',
                'address' => 'Jl. Matraman Raya No. 89, Jakarta',
                'phone' => '083265432109',
                'email' => 'fitri.lestari@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP017',
                'name' => 'Rizki Pratama',
                'department' => 'Maintenance',
                'department_id' => $maintenanceDept?->id,
                'position' => 'Engineer',
                'position_id' => $engineerPos?->id,
                'grade' => 'A3',
                'family_composition' => $family5?->name,
                'family_composition_id' => $family5?->id,
                'monthly_salary' => 9500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2019-02-25',
                'address' => 'Jl. HR Rasuna Said No. 150, Jakarta',
                'phone' => '084254321098',
                'email' => 'rizki.pratama@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP018',
                'name' => 'Nurul Hidayati',
                'department' => 'HR',
                'department_id' => $hrDept?->id,
                'position' => 'Assistant',
                'position_id' => $assistantPos?->id,
                'grade' => 'C2',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 5800000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-03-15',
                'address' => 'Jl. TB Simatupang No. 75, Jakarta',
                'phone' => '085243210987',
                'email' => 'nurul.hidayati@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP019',
                'name' => 'Fajar Nugroho',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Supervisor',
                'position_id' => $supervisorPos?->id,
                'grade' => 'B2',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 8200000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-08-10',
                'address' => 'Jl. Jenderal Sudirman No. 220, Jakarta',
                'phone' => '086232109876',
                'email' => 'fajar.nugroho@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP020',
                'name' => 'Yunita Sari',
                'department' => 'Finance',
                'department_id' => $financeDept?->id,
                'position' => 'Manager',
                'position_id' => $managerPos?->id,
                'grade' => 'A1',
                'family_composition' => $family6?->name,
                'family_composition_id' => $family6?->id,
                'monthly_salary' => 13500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2018-05-22',
                'address' => 'Jl. Asia Afrika No. 140, Jakarta',
                'phone' => '087221098765',
                'email' => 'yunita.sari@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP021',
                'name' => 'Dedi Supriyadi',
                'department' => 'IT',
                'department_id' => $itDept?->id,
                'position' => 'IT Support',
                'position_id' => $itSupportPos?->id,
                'grade' => 'B1',
                'family_composition' => $family1?->name,
                'family_composition_id' => $family1?->id,
                'monthly_salary' => 6900000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-09-08',
                'address' => 'Jl. Mampang Prapatan No. 25, Jakarta',
                'phone' => '088210987654',
                'email' => 'dedi.supriyadi@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP022',
                'name' => 'Sri Mulyani',
                'department' => 'Sales',
                'department_id' => $salesDept?->id,
                'position' => 'Sales Manager',
                'position_id' => $salesManagerPos?->id,
                'grade' => 'A1',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 11800000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2019-07-14',
                'address' => 'Jl. Boulevard Bintaro No. 98, Jakarta',
                'phone' => '089209876543',
                'email' => 'sri.mulyani@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP023',
                'name' => 'Hendra Wijaya',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Operator',
                'position_id' => $operatorPos?->id,
                'grade' => 'C3',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 5100000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2023-02-01',
                'address' => 'Jl. Tebet Barat Dalam No. 42, Jakarta',
                'phone' => '081398765432',
                'email' => 'hendra.wijaya@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP024',
                'name' => 'Lina Kusumawati',
                'department' => 'HR',
                'department_id' => $hrDept?->id,
                'position' => 'HR Manager',
                'position_id' => $hrManagerPos?->id,
                'grade' => 'A2',
                'family_composition' => $family5?->name,
                'family_composition_id' => $family5?->id,
                'monthly_salary' => 10500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2018-11-30',
                'address' => 'Jl. Panglima Polim Raya No. 88, Jakarta',
                'phone' => '082387654321',
                'email' => 'lina.kusumawati@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP025',
                'name' => 'Agung Setiawan',
                'department' => 'Logistics',
                'department_id' => $logisticsDept?->id,
                'position' => 'Logistics Staff',
                'position_id' => $logisticsStaffPos?->id,
                'grade' => 'C1',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 5700000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-10-15',
                'address' => 'Jl. Raya Kebayoran Lama No. 165, Jakarta',
                'phone' => '083376543210',
                'email' => 'agung.setiawan@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP026',
                'name' => 'Ratih Purnamasari',
                'department' => 'Finance',
                'department_id' => $financeDept?->id,
                'position' => 'Finance Officer',
                'position_id' => $financeOfficerPos?->id,
                'grade' => 'C1',
                'family_composition' => $family6?->name,
                'family_composition_id' => $family6?->id,
                'monthly_salary' => 8300000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-12-05',
                'address' => 'Jl. Ciledug Raya No. 109, Jakarta',
                'phone' => '084365432109',
                'email' => 'ratih.purnamasari@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP027',
                'name' => 'Arief Rahman',
                'department' => 'Quality Control',
                'department_id' => $qualityControlDept?->id,
                'position' => 'Staff',
                'position_id' => $staffPos?->id,
                'grade' => 'B2',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 6600000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-04-18',
                'address' => 'Jl. Kebon Nanas Raya No. 67, Jakarta',
                'phone' => '085354321098',
                'email' => 'arief.rahman@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP028',
                'name' => 'Wulan Sari',
                'department' => 'Maintenance',
                'department_id' => $maintenanceDept?->id,
                'position' => 'Engineer',
                'position_id' => $engineerPos?->id,
                'grade' => 'A3',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 9200000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2019-09-12',
                'address' => 'Jl. Jatinegara Barat No. 134, Jakarta',
                'phone' => '086343210987',
                'email' => 'wulan.sari@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP029',
                'name' => 'Yusuf Kurniawan',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Foreman',
                'position_id' => $foremanPos?->id,
                'grade' => 'B2',
                'family_composition' => $family1?->name,
                'family_composition_id' => $family1?->id,
                'monthly_salary' => 7300000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-06-20',
                'address' => 'Jl. Salemba Raya No. 45, Jakarta',
                'phone' => '087332109876',
                'email' => 'yusuf.kurniawan@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP030',
                'name' => 'Intan Permata',
                'department' => 'Admin',
                'department_id' => $adminDept?->id,
                'position' => 'Admin Staff',
                'position_id' => $adminStaffPos?->id,
                'grade' => 'C1',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 6100000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-07-05',
                'address' => 'Jl. Kramat Jaya No. 115, Jakarta',
                'phone' => '088321098765',
                'email' => 'intan.permata@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP031',
                'name' => 'Ridwan Pratama',
                'department' => 'IT',
                'department_id' => $itDept?->id,
                'position' => 'IT Support',
                'position_id' => $itSupportPos?->id,
                'grade' => 'B1',
                'family_composition' => $family5?->name,
                'family_composition_id' => $family5?->id,
                'monthly_salary' => 7100000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-10-22',
                'address' => 'Jl. Lenteng Agung Raya No. 89, Jakarta',
                'phone' => '089310987654',
                'email' => 'ridwan.pratama@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP032',
                'name' => 'Desi Kusuma',
                'department' => 'Sales',
                'department_id' => $salesDept?->id,
                'position' => 'Staff',
                'position_id' => $staffPos?->id,
                'grade' => 'C2',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 6500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-03-17',
                'address' => 'Jl. Raya Bogor No. 345, Jakarta',
                'phone' => '081409876543',
                'email' => 'desi.kusuma@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP033',
                'name' => 'Dian Prasetya',
                'department' => 'Finance',
                'department_id' => $financeDept?->id,
                'position' => 'Manager',
                'position_id' => $managerPos?->id,
                'grade' => 'A1',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 14000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2017-06-08',
                'address' => 'Jl. TB Simatupang No. 201, Jakarta',
                'phone' => '082498765432',
                'email' => 'dian.prasetya@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP034',
                'name' => 'Agus Prasetyo',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Operator',
                'position_id' => $operatorPos?->id,
                'grade' => 'C3',
                'family_composition' => $family1?->name,
                'family_composition_id' => $family1?->id,
                'monthly_salary' => 5250000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2023-01-10',
                'address' => 'Jl. Petojo Raya No. 76, Jakarta',
                'phone' => '083487654321',
                'email' => 'agus.prasetyo@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP035',
                'name' => 'Suci Rahayu',
                'department' => 'HR',
                'department_id' => $hrDept?->id,
                'position' => 'Assistant',
                'position_id' => $assistantPos?->id,
                'grade' => 'C2',
                'family_composition' => $family6?->name,
                'family_composition_id' => $family6?->id,
                'monthly_salary' => 5900000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-05-25',
                'address' => 'Jl. Haji Nawi No. 155, Jakarta',
                'phone' => '084476543210',
                'email' => 'suci.rahayu@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP036',
                'name' => 'Budiarto Manullang',
                'department' => 'Warehouse',
                'department_id' => $warehouseDept?->id,
                'position' => 'Warehouse Staff',
                'position_id' => $warehouseStaffPos?->id,
                'grade' => 'C2',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 5450000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-08-14',
                'address' => 'Jl. Kebagusan Raya No. 45, Jakarta',
                'phone' => '085465432109',
                'email' => 'budiarto.manullang@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP037',
                'name' => 'Maya Indriani',
                'department' => 'Quality Control',
                'department_id' => $qualityControlDept?->id,
                'position' => 'Engineer',
                'position_id' => $engineerPos?->id,
                'grade' => 'A2',
                'family_composition' => $family5?->name,
                'family_composition_id' => $family5?->id,
                'monthly_salary' => 9800000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-04-30',
                'address' => 'Jl. Raya Pasar Minggu No. 89, Jakarta',
                'phone' => '086454321098',
                'email' => 'maya.indriani@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP038',
                'name' => 'Hendry Gunawan',
                'department' => 'Maintenance',
                'department_id' => $maintenanceDept?->id,
                'position' => 'Supervisor',
                'position_id' => $supervisorPos?->id,
                'grade' => 'B3',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 8600000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2019-12-10',
                'address' => 'Jl. Raya Tengah No. 123, Jakarta',
                'phone' => '087443210987',
                'email' => 'hendry.gunawan@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP039',
                'name' => 'Dwi Astuti',
                'department' => 'Finance',
                'department_id' => $financeDept?->id,
                'position' => 'Finance Officer',
                'position_id' => $financeOfficerPos?->id,
                'grade' => 'C1',
                'family_composition' => $family1?->name,
                'family_composition_id' => $family1?->id,
                'monthly_salary' => 8100000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-11-08',
                'address' => 'Jl. Warung Buncit Raya No. 201, Jakarta',
                'phone' => '088432109876',
                'email' => 'dwi.astuti@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP040',
                'name' => 'Rahmat Hidayat',
                'department' => 'Logistics',
                'department_id' => $logisticsDept?->id,
                'position' => 'Manager',
                'position_id' => $managerPos?->id,
                'grade' => 'A2',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 12500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2018-03-15',
                'address' => 'Jl. Raya Darmo No. 175, Jakarta',
                'phone' => '089421098765',
                'email' => 'rahmat.hidayat@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP041',
                'name' => 'Santi Kumala',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Operator',
                'position_id' => $operatorPos?->id,
                'grade' => 'C2',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 5350000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-09-03',
                'address' => 'Jl. Raya Kalimalang No. 98, Jakarta',
                'phone' => '081510987654',
                'email' => 'santi.kumala@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP042',
                'name' => 'Taufik Hidayat',
                'department' => 'IT',
                'department_id' => $itDept?->id,
                'position' => 'Engineer',
                'position_id' => $engineerPos?->id,
                'grade' => 'A3',
                'family_composition' => $family6?->name,
                'family_composition_id' => $family6?->id,
                'monthly_salary' => 10500000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2019-01-20',
                'address' => 'Jl. Boulevard Argo Mas No. 66, Jakarta',
                'phone' => '082509876543',
                'email' => 'taufik.hidayat@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP043',
                'name' => 'Vina Marlina',
                'department' => 'Sales',
                'department_id' => $salesDept?->id,
                'position' => 'Staff',
                'position_id' => $staffPos?->id,
                'grade' => 'C1',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 6300000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-07-22',
                'address' => 'Jl. Ciputat Raya No. 45, Jakarta',
                'phone' => '083598765432',
                'email' => 'vina.marlina@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP044',
                'name' => 'Zulham Pratama',
                'department' => 'Admin',
                'department_id' => $adminDept?->id,
                'position' => 'Admin Staff',
                'position_id' => $adminStaffPos?->id,
                'grade' => 'C1',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 6050000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-02-18',
                'address' => 'Jl. Raya Cawang No. 134, Jakarta',
                'phone' => '084587654321',
                'email' => 'zulham.pratama@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP045',
                'name' => 'Yeni Lestari',
                'department' => 'HR',
                'department_id' => $hrDept?->id,
                'position' => 'Manager',
                'position_id' => $managerPos?->id,
                'grade' => 'A2',
                'family_composition' => $family5?->name,
                'family_composition_id' => $family5?->id,
                'monthly_salary' => 11000000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2018-10-05',
                'address' => 'Jl. Boulevard Raya No. 77, Jakarta',
                'phone' => '085576543210',
                'email' => 'yeni.lestari@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP046',
                'name' => 'Roni Siregar',
                'department' => 'Production',
                'department_id' => $productionDept?->id,
                'position' => 'Supervisor',
                'position_id' => $supervisorPos?->id,
                'grade' => 'B2',
                'family_composition' => $family1?->name,
                'family_composition_id' => $family1?->id,
                'monthly_salary' => 8400000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-05-12',
                'address' => 'Jl. Pemuda Raya No. 89, Jakarta',
                'phone' => '086565432109',
                'email' => 'roni.siregar@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP047',
                'name' => 'Widya Sari',
                'department' => 'Finance',
                'department_id' => $financeDept?->id,
                'position' => 'Finance Officer',
                'position_id' => $financeOfficerPos?->id,
                'grade' => 'C2',
                'family_composition' => $family3?->name,
                'family_composition_id' => $family3?->id,
                'monthly_salary' => 8200000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2021-12-01',
                'address' => 'Jl. Raya Pasar Baru No. 34, Jakarta',
                'phone' => '087554321098',
                'email' => 'widya.sari@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP048',
                'name' => 'Andika Prasetya',
                'department' => 'Logistics',
                'department_id' => $logisticsDept?->id,
                'position' => 'Logistics Staff',
                'position_id' => $logisticsStaffPos?->id,
                'grade' => 'C2',
                'family_composition' => $family2?->name,
                'family_composition_id' => $family2?->id,
                'monthly_salary' => 5650000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2022-06-14',
                'address' => 'Jl. Rawa Belong No. 156, Jakarta',
                'phone' => '088543210987',
                'email' => 'andika.prasetya@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP049',
                'name' => 'Silvia Anggraini',
                'department' => 'Quality Control',
                'department_id' => $qualityControlDept?->id,
                'position' => 'Staff',
                'position_id' => $staffPos?->id,
                'grade' => 'B1',
                'family_composition' => $family4?->name,
                'family_composition_id' => $family4?->id,
                'monthly_salary' => 6700000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2020-11-08',
                'address' => 'Jl. Kebon Jeruk Raya No. 101, Jakarta',
                'phone' => '089532109876',
                'email' => 'silvia.anggraini@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ndp' => 'EMP050',
                'name' => 'Ferry Kurniawan',
                'department' => 'Maintenance',
                'department_id' => $maintenanceDept?->id,
                'position' => 'Engineer',
                'position_id' => $engineerPos?->id,
                'grade' => 'A3',
                'family_composition' => $family6?->name,
                'family_composition_id' => $family6?->id,
                'monthly_salary' => 9600000,
                'status' => 'active',
                'employment_status_id' => $statusActive?->id,
                'hire_date' => '2019-08-25',
                'address' => 'Jl. Raya Kebayoran Baru No. 122, Jakarta',
                'phone' => '081621098765',
                'email' => 'ferry.kurniawan@example.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('employees')->insert($employees);
    }
}